server:
  port: 8766
spring:
  application:
    name: admin-server

eureka:
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://admin-eureka:1234/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS