server:
  port: 1234

spring:
  cloud:
    client:
      ipAddress: localhost
  security:
    user:
      name: admin
      password: adminadmin

eureka:
  instance:
    prefer-ip-address: false
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://admin:adminadmin@localhost:1234/eureka/

