server:
  port: 7373

spring:
  application:
    name: admin-client
  cloud:
    client:
      ipAddress: localhost

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1234/eureka/


