spring:
  application:
    name: admin-client
  security:
    user:
      name: "client"
      password: "client"

management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  file: var/log/sample-boot-application.log
#  pattern:
#    file: clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    prefer-ip-address: true
    metadata-map:
      user.name:  ${spring.security.user.name}
      user.password:  ${spring.security.user.password}
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      serviceZone: http://localhost:1234/eureka/
server:
  port: 7373

