server:
  port: 7373

spring:
  application:
    name: admin-client

eureka:
  client:
    service-url:
      defaultZone: http://admin-eureka:1234/eureka/

# docker环境下为容器内部路径
logging:
  file: /spring-boot-admin-in-docker/log/admin-client.log
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
management:
  endpoints:
    web:
      exposure:
        include: "*"